export enum SecurityCategory {
  SQL_INJECTION = 'SQL_INJECTION',
  XSS = 'XSS',
  COMMAND_INJECTION = 'COMMAND_INJECTION',
  PATH_TRAVERSAL = 'PATH_TRAVERSAL',
  UNSAFE_DESERIALIZATION = 'UNSAFE_DESERIALIZATION',
  INSECURE_CONFIGURATION = 'INSECURE_CONFIGURATION',
  AUTHENTICATION = 'AUTHENTICATION',
  AUTHORIZATION = 'AUTHORIZATION',
  SENSITIVE_DATA = 'SENSITIVE_DATA',
  OTHER = 'OTHER'
}

export enum InputVulnerabilityType {
  SQL_INJECTION = 'SQL_INJECTION',
  XSS = 'XSS',
  PATH_TRAVERSAL = 'PATH_TRAVERSAL',
  COMMAND_INJECTION = 'COMMAND_INJECTION',
  UNSAFE_DESERIALIZATION = 'UNSAFE_DESERIALIZATION',
  FILE_UPLOAD = 'FILE_UPLOAD',
  DATA_EXPOSURE = 'DATA_EXPOSURE',
  OPEN_REDIRECT = 'OPEN_REDIRECT'
}

export type SeverityLevel = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO'; 